config/routes.rb
RecordLabelApp::Application.routes.draw do
  resources :users, :only => [:new, :create, :show]
  resource :session, :only => [:new, :create, :destroy]

  root :to => "users#new"
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password

  before_validation { self.session_token ||= self.class.generate_session_token }

  validates :email, :first_name, :last_name, :presence => true
  validates :password, :presence => { :minimum => 6, :allow_nil => true }
  validates :password_digest, :presence => { :message => "Password cannot be empty" }


  def self.find_by_credentials(username, password)
    user = self.find_by_email(username)

    return nil unless user

    user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
  end

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def name
    "#{self.first_name} #{self.last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])

    if @user
      login_user(@user)
      flash[:notice] = "#{@user.name} signed in"
      redirect_to root_url
    else
      @user = User.new
      flash.now[:errors] = ["Email or password invalid"]
      render :new
    end
  end

  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil

    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login_user(@user)

      flash[:notice] = "#{@user.name} successfully signed up"
      redirect_to root_url
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  private
    def user_params
      params.require(:user).permit(:email, :first_name, :last_name, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def current_user?(user)
    logged_in? && current_user.id == user.id
  end

  def logged_in?
    !current_user.nil?
  end

  def login_user(user)
    session[:session_token] = user.session_token
    @current_user = user
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RecordLabelApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<hr>
<%= link_to "home", root_url %> |
<% if logged_in? %>
  <%= link_to "profile", users_url(current_user) %> |
  <%= link_to "sign out", session_url, :method => :delete %>
<% else %>
  <%= link_to "sign up", new_user_url %> |
  <%= link_to "sign in", new_session_url %>
<% end %>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign up</h1>

<form action="<%= users_url %>" method="post">
  <% if flash[:errors] %>
    <ul>
      <% flash[:errors].each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  <% end %>

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>"

  <label for="user_first_name">First name</label>
  <input type="text"
         id="user_first_name"
         name="user[first_name]"
         value="<%= @user.first_name %>"
         placeholder="First name">
  <br>

  <label for="user_last_name">Last name</label>
  <input type="text"
         id="user_last_name"
         name="user[last_name]"
         value="<%= @user.last_name %>"
         placeholder="Last name">
  <br>

  <label for="user_email">Email</label>
  <input type="text"
         id="user_email"
         name="user[email]"
         value="<%= @user.email %>"
         placeholder="Email">
  <br>

  <label for="user_password">Password</label>
  <input type="password"
         id="user_password"
         name="user[password]">
  <br>

  <input type="submit" value="Create user">
</form>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<%= "(you!)" if current_user?(@user) %>

Email: <%= @user.email %>